sistema:
  nome: "Boletim Escolar 2025"
  descricao: "Gestão de notas bimestrais, médias, finais e conselho."

estrutura_dados:
  identificacao:
    - nome: "aluno"      origem_coluna: "Protagonistas" tipo: string
    - nome: "matricula"  origem_coluna: "Matrícula"     tipo: string
    - nome: "turma"      origem_coluna: "S/T"           tipo: string
    - nome: "tutoria"    origem_coluna: "Tutoria"       tipo: string
    - nome: "conselho"   origem_coluna: "Conselho"      tipo: string

  disciplinas:
    - {sigla: "Bio",  nome: "Biologia",           prefixo: "Bio"}
    - {sigla: "Fís",  nome: "Física",             prefixo: "Fís"}
    - {sigla: "Mat",  nome: "Matemática",         prefixo: "Mat"}
    - {sigla: "Quí",  nome: "Química",            prefixo: "Quí"}
    - {sigla: "Por",  nome: "Língua Portuguesa",  prefixo: "Por"}
    - {sigla: "Geo",  nome: "Geografia",          prefixo: "Geo"}
    - {sigla: "His",  nome: "História",           prefixo: "His"}
    - {sigla: "Ing",  nome: "Inglês",             prefixo: "Ing"}
    - {sigla: "EdF",  nome: "Educação Física",    prefixo: "EdF"}
    - {sigla: "Art",  nome: "Artes",              prefixo: "Art"}
    - {sigla: "Esp",  nome: "Espanhol",           prefixo: "Esp"}
    - {sigla: "Soc",  nome: "Sociologia",         prefixo: "Soc"}
    - {sigla: "Fil",  nome: "Filosofia",          prefixo: "Fil"}
    - {sigla: "Elet", nome: "Eletiva",            prefixo: "Elet"}
    - {sigla: "PV",   nome: "Projeto de Vida",    prefixo: "PV"}
    - {sigla: "PT",   nome: "Pensamento Técnico", prefixo: "PT"}
    - {sigla: "RALP", nome: "RALP",               prefixo: "RALP"}
    - {sigla: "RAM",  nome: "RAM",                prefixo: "RAM"}
    - {sigla: "Apro", nome: "Aprovação",          prefixo: "Apro"}
    - {sigla: "PI",   nome: "PI",                 prefixo: "PI"}

  modelo_colunas_disciplina:
    n1:   "<prefixo>1"
    n2:   "<prefixo>2"
    n3:   "<prefixo>3"
    n4:   "<prefixo>4"
    parcial:      "P<prefixo>"
    media_geral:  "MG<prefixo>"
    pre:          "Pre-<prefixo>"
    final:        "F<prefixo>"
    media_final:  "MF<prefixo>"
    situacao:     "S<prefixo>"
